#!/usr/bin/env node
"use strict";

const fs=require("fs");
const path=require("path");

const root=path.resolve(__dirname,"..");
const sourcePath=path.join(root,"index.html");
const outputPath=path.join(root,"next","index.html");

function replaceOnce(source,needle,replacement){
  const first=source.indexOf(needle);
  if(first<0)throw new Error("next build marker missing: "+needle);
  if(source.indexOf(needle,first+needle.length)>=0)throw new Error("next build marker is not unique: "+needle);
  return source.slice(0,first)+replacement+source.slice(first+needle.length);
}

function replaceRange(source,startMarker,endMarker,replacement){
  const start=source.indexOf(startMarker),end=source.indexOf(endMarker,start+startMarker.length);
  if(start<0||end<0)throw new Error("next build range marker missing: "+startMarker+" -> "+endMarker);
  return source.slice(0,start)+replacement+source.slice(end);
}

function generate(source){
  let html=source;
  html=replaceOnce(html,"<!DOCTYPE html>","<!DOCTYPE html>\n<!-- GENERATED by scripts/build-next.js. Do not edit next/index.html directly. -->");
  html=replaceOnce(html,"<head>","<head>\n<base href=\"../\">\n<meta name=\"aiba-entry\" content=\"next\">");
  html=replaceOnce(html,"<title>aiBA·百分大战 v1.94 PORTRAIT LOCK</title>","<title>aiBA·百分大战 v1.94 NEXT</title>");
  html=replaceOnce(html,'<script src="vendor/three.min.r128.js"></script>',[
    '<script>window.__AIBA_NEXT__=true;window.__AIBA_DISABLE_PRODUCTION_WRITES__=true;window.addEventListener("error",function(e){var root=document.documentElement,items=[];try{items=JSON.parse(root.getAttribute("data-aiba-early-errors")||"[]");}catch(_){items=[];}items.push({message:e.message||"",source:e.filename||"",line:e.lineno||0,column:e.colno||0,stack:e.error&&e.error.stack||""});root.setAttribute("data-aiba-early-errors",JSON.stringify(items.slice(-30)));},true);</script>',
    '<script src="src/core/runtime.js?v=refactor7"></script>',
    '<script src="vendor/three.min.r128.js"></script>'
  ].join("\n"));
  html=replaceOnce(html,'<script src="src/player-id.js"></script>','<script src="src/core/player-id-sandbox.js"></script>');
  html=replaceOnce(html,'<script src="src/leaderboard-api.js"></script>','<script src="src/core/leaderboard-sandbox.js"></script>');
  html=replaceOnce(html,'<script src="src/recorder.js?v=1.94"></script>','<script src="src/recorder.js?v=refactor9"></script>');
  html=replaceOnce(html,'<script src="src/vision.js?v=1.94"></script>','<script src="src/vision.js?v=refactor11"></script>');
  html=replaceOnce(html,'<script src="src/navigation.js?v=1.90"></script>','<script src="src/navigation.js?v=refactor8"></script>');
  html=replaceRange(html,
    'function showMenu(){',
    'function sceneSelectMarkup(){',
    '/* Home menu and mode information are owned by src/ui/menu.js in the experimental entry. */\n');
  html=replaceRange(html,
    'function sceneSelectMarkup(){',
    'function pickDiff(k){',
    '/* Difficulty and court selection are owned by src/ui/setup.js in the experimental entry. */\n');
  html=replaceRange(html,
    'function pickDiff(k){',
    '/* ---------------- RACK RUSH: 投篮机闯关 ---------------- */',
    '/* Pregame roster drawing and matchup panels are owned by src/ui/pregame.js in the experimental entry. */\n');
  html=replaceRange(html,
    '/* ---------------- RACK RUSH: 投篮机闯关 ---------------- */',
    'const BATTLE_RUNS_KEY=',
    '/* RACK RUSH is owned by src/modes/rack-rush.js in the experimental entry. */\n');
  html=replaceRange(html,
    'const BATTLE_RUNS_KEY=',
    'function beginStage(){',
    '/* Percent Battle state and startup are owned by src/modes/percent-battle/state.js. */\n');
  html=replaceRange(html,
    'function beginStage(){',
    '/* ---------------- replay system ---------------- */',
    '/* Contest round flow is owned by src/modes/contest.js in the experimental entry. */\n/* ---------------- replay system ---------------- */');
  html=replaceRange(html,
    'function simAI(o){',
    '/* ---------------- input ---------------- */',
    '/* Contest bracket and finals are owned by src/modes/contest.js in the experimental entry. */\n/* ---------------- input ---------------- */');
  html=replaceRange(html,
    'function battleRefreshSpot(i){',
    '/* ---- 点击点位移动:屏幕投影光圈 + 屏幕外边缘箭头 ---- */',
    '/* Percent Battle spot rules are owned by src/modes/percent-battle/spots.js. */\n/* ---- 点击点位移动:屏幕投影光圈 + 屏幕外边缘箭头 ---- */');
  html=replaceRange(html,
    '/* ---------------- 百分大战:真实对手(同场竞投) ---------------- */',
    '/* ---- 空中球碰撞:撞击改变结果(原本进的被撞歪→不进) ---- */',
    '/* Percent Battle opponent logic is owned by src/modes/percent-battle/opponent.js. */\n/* ---- 空中球碰撞:撞击改变结果(原本进的被撞歪→不进) ---- */');
  html=replaceRange(html,
    'function finishBattle(win,ball){',
    '/* ---------------- 英雄时刻:制胜球电影化慢动作 ---------------- */',
    '/* Percent Battle result flow is owned by src/modes/percent-battle/results.js. */\n/* ---------------- 英雄时刻:制胜球电影化慢动作 ---------------- */');
  html=replaceRange(html,
    'function startPractice(){',
    '/* shadow blob */',
    '/* Practice flow is owned by src/modes/practice.js in the experimental entry. */\n\n/* shadow blob */');
  html=replaceRange(html,
    '/* ---------------- UI helpers ---------------- */',
    'function pauseableState(){',
    '/* Panels and loading are owned by src/ui modules in the experimental entry. */\n');
  html=replaceRange(html,
    'function pauseableState(){',
    'function stars(r){',
    '/* Pause and return-home flow are owned by src/ui/pause.js in the experimental entry. */\n');
  html=replaceRange(html,
    '  // 练习结束检测',
    '  // states',
    '  updatePractice(dt);\n  // states');
  html=replaceOnce(html,
    'bootGame();\nanimate();',
    '/* NEXT boot and loop are started by src/core/bootstrap-next.js. */\n//# sourceURL=aiba-next-inline.js');
  html=replaceOnce(html,
    '</script>\n<script src="src/game-flow.js?v=1.93"></script>',
    '</script>\n<script src="src/core/legacy-adapter.js?v=refactor15"></script>\n<script src="src/modes/rack-rush.js"></script>\n<script src="src/modes/contest.js"></script>\n<script src="src/modes/practice.js?v=refactor5"></script>\n<script src="src/modes/percent-battle/state.js?v=refactor4"></script>\n<script src="src/modes/percent-battle/spots.js?v=refactor4"></script>\n<script src="src/modes/percent-battle/opponent.js?v=refactor4"></script>\n<script src="src/modes/percent-battle/results.js?v=refactor4"></script>\n<script src="src/modes/percent-battle/index.js?v=refactor4"></script>\n<script src="src/ui/panels.js?v=refactor7"></script>\n<script src="src/ui/loading.js?v=refactor7"></script>\n<script src="src/ui/menu.js?v=refactor12"></script>\n<script src="src/ui/setup.js?v=refactor13"></script>\n<script src="src/ui/pregame.js?v=refactor15"></script>\n<script src="src/ui/pause.js?v=refactor10"></script>\n<script src="src/core/bootstrap-next.js?v=refactor12"></script>\n<script src="src/game-flow.js?v=1.93"></script>');
  return html;
}

function build(){
  const source=fs.readFileSync(sourcePath,"utf8");
  const output=generate(source);
  fs.mkdirSync(path.dirname(outputPath),{recursive:true});
  fs.writeFileSync(outputPath,output);
  return outputPath;
}

if(require.main===module)console.log(path.relative(root,build()));

module.exports={generate,build};
