#!/usr/bin/env node
"use strict";

const fs=require("fs");
const path=require("path");

const root=path.resolve(__dirname,"..");
const sourcePath=path.join(root,"index.html");
const outputPath=path.join(root,"next","index.html");

function replaceOnce(source,needle,replacement){
  const first=source.indexOf(needle);
  if(first<0)throw new Error("next build marker missing: "+needle);
  if(source.indexOf(needle,first+needle.length)>=0)throw new Error("next build marker is not unique: "+needle);
  return source.slice(0,first)+replacement+source.slice(first+needle.length);
}

function replaceRange(source,startMarker,endMarker,replacement){
  const start=source.indexOf(startMarker),end=source.indexOf(endMarker,start+startMarker.length);
  if(start<0||end<0)throw new Error("next build range marker missing: "+startMarker+" -> "+endMarker);
  return source.slice(0,start)+replacement+source.slice(end);
}

function generate(source){
  let html=source;
  html=replaceOnce(html,"<!DOCTYPE html>","<!DOCTYPE html>\n<!-- GENERATED by scripts/build-next.js. Do not edit next/index.html directly. -->");
  html=replaceOnce(html,"<head>","<head>\n<base href=\"../\">\n<meta name=\"aiba-entry\" content=\"next\">");
  html=replaceOnce(html,"<title>aiBA·百分大战 v1.94 PORTRAIT LOCK</title>","<title>aiBA·百分大战 v1.94 NEXT</title>");
  html=replaceOnce(html,'<script src="vendor/three.min.r128.js"></script>',[
    '<script>window.__AIBA_NEXT__=true;window.__AIBA_DISABLE_PRODUCTION_WRITES__=true;</script>',
    '<script src="src/core/runtime.js"></script>',
    '<script src="vendor/three.min.r128.js"></script>'
  ].join("\n"));
  html=replaceOnce(html,'<script src="src/player-id.js"></script>','<script src="src/core/player-id-sandbox.js"></script>');
  html=replaceOnce(html,'<script src="src/leaderboard-api.js"></script>','<script src="src/core/leaderboard-sandbox.js"></script>');
  html=replaceRange(html,
    '/* ---------------- RACK RUSH: 投篮机闯关 ---------------- */',
    'const BATTLE_RUNS_KEY=',
    '/* RACK RUSH is owned by src/modes/rack-rush.js in the experimental entry. */\n');
  html=replaceOnce(html,
    '</script>\n<script src="src/game-flow.js?v=1.93"></script>',
    '</script>\n<script src="src/core/legacy-adapter.js"></script>\n<script src="src/modes/rack-rush.js"></script>\n<script src="src/game-flow.js?v=1.93"></script>');
  return html;
}

function build(){
  const source=fs.readFileSync(sourcePath,"utf8");
  const output=generate(source);
  fs.mkdirSync(path.dirname(outputPath),{recursive:true});
  fs.writeFileSync(outputPath,output);
  return outputPath;
}

if(require.main===module)console.log(path.relative(root,build()));

module.exports={generate,build};
